name: Build

on: 
  push:
    branches: '**'

jobs:
  test-win2012r2:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v2
    - name: Remove Existing Resource Group
      shell: pwsh
      run: |
        ./src/remove.ps1 -ARM_CLIENT_ID ${{ secrets.ARM_CLIENT_ID }} -ARM_CLIENT_SECRET ${{ secrets.ARM_CLIENT_SECRET }} -ARM_SUBSCRIPTION_ID ${{ secrets.ARM_SUBSCRIPTION_ID }} -ARM_TENANT_ID ${{ secrets.ARM_TENANT_ID }} -LabName SharePointDscDevInfraCIWin2012R2
