name: Build

on: 
  push:
    branches: '**'

jobs:
  test-win2012r2-clean:
    runs-on: ubuntu-20.04
    container: mcr.microsoft.com/azure-powershell:8.2.0-alpine-3.14
    steps:
    - uses: actions/checkout@v2
    - run: whoami
      shell: pwsh
    - run: $PSVersionTable
      shell: pwsh
    - run: Get-ChildItem /root/.local/share/powershell/Modules
      shell: pwsh
    - run: Get-Module -ListAvailable -Refresh
      shell: pwsh
    - name: Remove Existing Resource Group
      shell: pwsh
      run: ./src/remove.ps1 -ARM_CLIENT_ID ${{ secrets.ARM_CLIENT_ID }} -ARM_CLIENT_SECRET ${{ secrets.ARM_CLIENT_SECRET }} -ARM_SUBSCRIPTION_ID ${{ secrets.ARM_SUBSCRIPTION_ID }} -ARM_TENANT_ID ${{ secrets.ARM_TENANT_ID }} -LabName SharePointDscDevInfraCIWin2012R2
  test-win2012r2:
    needs: test-win2012r2-clean
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v2
    - name: Installing Prerequisites
      shell: pwsh
      run: Install-Module -Name Az -RequiredVersion 8.2.0 -Force -AllowClobber;
    - name: Remove Existing Resource Group
      shell: pwsh
      run: ./src/remove.ps1 -ARM_CLIENT_ID ${{ secrets.ARM_CLIENT_ID }} -ARM_CLIENT_SECRET ${{ secrets.ARM_CLIENT_SECRET }} -ARM_SUBSCRIPTION_ID ${{ secrets.ARM_SUBSCRIPTION_ID }} -ARM_TENANT_ID ${{ secrets.ARM_TENANT_ID }} -LabName SharePointDscDevInfraCIWin2012R2
